name: Mirror main → upstream es/move-edits

on:
  push:
    branches: [ main ]     # run whenever your fork's main updates
  workflow_dispatch: {}     # allow manual runs

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Add upstream remote and fetch target branch
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          git remote add upstream https://x-access-token:${UPSTREAM_PAT}@github.com/mlinder10/vitoro.git
          git fetch upstream es/move-edits || true

      - name: Push fork main → upstream/es/move-edits
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          current_upstream_head="$(git ls-remote --heads upstream es/move-edits | awk '{print $1}')"
          if [ -z "$current_upstream_head" ]; then
            git push upstream HEAD:refs/heads/es/move-edits
          else
            git push upstream HEAD:refs/heads/es/move-edits --force-with-lease=refs/heads/es/move-edits:$current_upstream_head
          fi
