name: Mirror main → upstream es/move-edits

on:
  push:
    branches: [ main ]     # triggers when your fork's main changes (e.g., after your PR merges)
  workflow_dispatch: {}     # allow manual runs

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity (cosmetic)
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Add upstream remote and fetch target branch
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          # authenticate remote using your PAT
          git remote add upstream https://x-access-token:${UPSTREAM_PAT}@github.com/mlinder10/vitoro.git
          git fetch upstream es/move-edits || true

      - name: Push fork main to upstream/es/move-edits
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          # Option 1: overwrite upstream/es/move-edits to match your main exactly
          # (use --force-with-lease to avoid clobbering if upstream changed unexpectedly)
          current_upstream_head="$(git ls-remote --heads upstream es/move-edits | awk '{print $1}')"
          if [ -z "$current_upstream_head" ]; then
            # Branch doesn't exist yet upstream; create it
            git push upstream HEAD:refs/heads/es/move-edits
          else
            git push upstream HEAD:refs/heads/es/move-edits

